-- Under the multi-tenant schema (see 0004_multitenant_rebuild.sql), every
-- songs/worship_sets row requires a church_id, which can only be resolved
-- from an authenticated user's profile. There is no meaningful global seed
-- data anymore -- each church gets its own songs/worship sets by using the
-- product after signing up and completing onboarding.
--
-- For local/manual QA data, sign up through the app, complete onboarding,
-- then add songs through the UI (or via the SQL editor, setting church_id
-- explicitly to the church you want to seed).
