-- A Bible that lives in our own database.
--
-- Churches put scripture on the screen every single service, and until now the
-- only way to do it in SagipMusica was to type the verse into a song section
-- and hope nobody fat-fingered it. This migration adds the text itself, so
-- "John 3:16" is something the presenter looks up rather than something they
-- transcribe.
--
-- The verses are NOT in this file. 0021_bible_kjv_verses.sql carries the
-- 31,102 rows of the 1769 Authorized Version and is generated by
-- scripts/generate-bible-migration.mjs. What is here is the shape, the 66
-- books, and the rules -- the parts a person reads and edits by hand.
--
-- Design notes:
--
--  * NO NETWORK CALL, EVER. The alternative -- api.bible, bolls.life, ESV's
--    API -- puts somebody else's uptime, rate limit and API key in the path of
--    a verse going on the screen mid-sermon, in buildings whose internet is a
--    phone hotspot. Our own table answers in a millisecond and answers when
--    the line is down. It also means the desktop build can ship the same rows
--    in a local SQLite file and behave identically offline, which is the next
--    thing to be built.
--
--  * TRANSLATIONS ARE A TABLE, not a column we will regret. Only the KJV is
--    seeded today, but this is Philippine churches: Ang Dating Biblia and the
--    Magandang Balita Biblia are going to be asked for, and asked for soon.
--    Adding one then is an insert into bible_translations plus a generated
--    verse file -- no schema change, no app change, no re-write of the
--    reference parser.
--
--  * BOOKS ARE SHARED ACROSS TRANSLATIONS. bible_books has no translation_id:
--    all 66 books, their order and their ids are the same in every Protestant
--    Bible, and duplicating them per translation would only create the
--    possibility of them disagreeing. The cost is that a Tagalog translation's
--    book names are not stored yet. That is a display concern, and when it
--    arrives it belongs in a bible_book_names(translation_id, book_id, name)
--    side table -- not in a second copy of the canon.
--
--  * COUNTS ARE DERIVED. There is no chapter_count column on bible_books and
--    no verse_count column anywhere, for the same reason 0018 refuses to store
--    pin counts: a cached count is wrong the first time a row moves and
--    nothing says so. The bible_chapters view below aggregates them, and it is
--    small enough (1,189 rows for the KJV) that the app fetches the whole
--    thing once and builds every chapter and verse grid from it offline.
--
--  * READ-ONLY TO EVERYONE. There is a select policy and there are no others,
--    so no signed-in user and no admin can write a word of it -- scripture
--    changes when a migration says so and not otherwise. anon can read as well
--    as authenticated, because the projector window (see AppRoutes) runs
--    without a session and the marketing site may want a verse one day.
--    Nothing here is private; it is the best-known text in the world.

-- ============================================================================
-- 1. Translations
-- ============================================================================

create table if not exists bible_translations (
  -- Short, stable and human-readable, because it appears in the generated
  -- verse files, in URLs (/bible?translation=kjv) and in bug reports.
  id text primary key
    check (id ~ '^[a-z0-9-]{2,16}$'),

  name text not null,

  -- What the projector prints under the reference: "John 3:16 (KJV)".
  abbreviation text not null,

  -- ISO 639-1. 'en' today; 'tl' is the one to expect next.
  language_code text not null default 'en'
    check (language_code ~ '^[a-z]{2}$'),

  -- The year of the specific revision, not of the first edition. The KJV row
  -- says 1769 -- the Blayney revision every modern "KJV" actually is -- and
  -- not 1611, so there is never a question about which text this is.
  year integer,

  -- Free text on purpose. Every translation we can legally ship is public
  -- domain, but the reason differs by jurisdiction and is worth recording
  -- next to the text rather than in a commit message.
  license text not null,

  -- Where the rows came from, so the import is reproducible by someone who
  -- was not here when it was done.
  source_url text,

  -- One translation is the one a church gets when it has not chosen. Enforced
  -- as at-most-one by the partial unique index below.
  is_default boolean not null default false,

  created_at timestamptz not null default now()
);

-- Partial unique index: every indexed row has is_default = true, so at most
-- one row can be indexed at a time. Rows with false are not in the index and
-- are unconstrained.
create unique index if not exists bible_translations_one_default
  on bible_translations (is_default) where is_default;

insert into bible_translations (id, name, abbreviation, language_code, year, license, source_url, is_default)
values (
  'kjv',
  'King James Version',
  'KJV',
  'en',
  1769,
  'Public domain. The 1769 Blayney revision of the 1611 Authorized Version is '
    || 'out of copyright worldwide. The Crown letters patent that still cover '
    || 'the KJV restrict printing within the United Kingdom only, and do not '
    || 'reach the text itself or its use elsewhere.',
  'https://github.com/farskipper/kjv',
  true
)
on conflict (id) do update set
  name = excluded.name,
  abbreviation = excluded.abbreviation,
  language_code = excluded.language_code,
  year = excluded.year,
  license = excluded.license,
  source_url = excluded.source_url;

-- ============================================================================
-- 2. Books
--
-- Fixed at 66 rows, in canonical order, with the id doubling as the sort key.
-- The ids are load-bearing: the generated verse file writes them literally,
-- so renumbering these would silently re-attach every verse to the wrong book.
-- ============================================================================

create table if not exists bible_books (
  -- 1 = Genesis .. 66 = Revelation. Deliberately not a uuid: this is a closed,
  -- ordered, universally agreed list, and an integer that sorts into reading
  -- order is worth more here than a surrogate key.
  id smallint primary key
    check (id between 1 and 66),

  name text not null unique,

  abbreviation text not null unique,

  testament text not null
    check (testament in ('old', 'new')),

  -- Everything else a person might type for this book: older names, common
  -- short forms, and the spellings that show up when somebody is typing fast
  -- on a phone at the back of the sanctuary. The reference parser in
  -- src/features/bible/reference.ts normalises both sides before comparing --
  -- case, spaces, punctuation and "I/II/III" vs "1/2/3" are all handled there
  -- -- so these only need to carry spellings that are genuinely different
  -- words, not every capitalisation of them.
  aliases text[] not null default '{}'
);

insert into bible_books (id, name, abbreviation, testament, aliases) values
  ( 1, 'Genesis',         'Gen',     'old', '{ge,gn}'),
  ( 2, 'Exodus',          'Ex',      'old', '{exo,exod}'),
  ( 3, 'Leviticus',       'Lev',     'old', '{le,lv}'),
  ( 4, 'Numbers',         'Num',     'old', '{nu,nm,nb}'),
  ( 5, 'Deuteronomy',     'Deut',    'old', '{dt,de,deu}'),
  ( 6, 'Joshua',          'Josh',    'old', '{jos,jsh}'),
  ( 7, 'Judges',          'Judg',    'old', '{jdg,jg,jdgs}'),
  ( 8, 'Ruth',            'Ruth',    'old', '{rth,ru}'),
  ( 9, '1 Samuel',        '1 Sam',   'old', '{1sa,1s,1sm}'),
  (10, '2 Samuel',        '2 Sam',   'old', '{2sa,2s,2sm}'),
  (11, '1 Kings',         '1 Kgs',   'old', '{1ki,1kin,1k}'),
  (12, '2 Kings',         '2 Kgs',   'old', '{2ki,2kin,2k}'),
  (13, '1 Chronicles',    '1 Chr',   'old', '{1ch,1chron}'),
  (14, '2 Chronicles',    '2 Chr',   'old', '{2ch,2chron}'),
  (15, 'Ezra',            'Ezra',    'old', '{ezr}'),
  (16, 'Nehemiah',        'Neh',     'old', '{ne}'),
  (17, 'Esther',          'Est',     'old', '{es,esth}'),
  (18, 'Job',             'Job',     'old', '{jb}'),
  -- "Psalm 23" is how everyone says it and "Ps" is how everyone writes it.
  (19, 'Psalms',          'Ps',      'old', '{psalm,psa,psm,pss,pslm}'),
  (20, 'Proverbs',        'Prov',    'old', '{pr,prv,pro}'),
  (21, 'Ecclesiastes',    'Eccl',    'old', '{ec,ecc,eccles,qoheleth}'),
  -- The source file calls this "Solomon's Song"; the KJV title page calls it
  -- "The Song of Solomon"; scholars call it Song of Songs or Canticles. All
  -- four find it.
  (22, 'Song of Solomon', 'Song',    'old', '{song of songs,songs,canticles,cant,sos,sng,solomons song}'),
  (23, 'Isaiah',          'Isa',     'old', '{is,isai}'),
  (24, 'Jeremiah',        'Jer',     'old', '{je,jr}'),
  (25, 'Lamentations',    'Lam',     'old', '{la,lament}'),
  (26, 'Ezekiel',         'Ezek',    'old', '{eze,ezk}'),
  (27, 'Daniel',          'Dan',     'old', '{da,dn}'),
  (28, 'Hosea',           'Hos',     'old', '{ho}'),
  (29, 'Joel',            'Joel',    'old', '{jl,joe}'),
  (30, 'Amos',            'Amos',    'old', '{am}'),
  (31, 'Obadiah',         'Obad',    'old', '{ob,oba}'),
  (32, 'Jonah',           'Jonah',   'old', '{jon,jnh}'),
  (33, 'Micah',           'Mic',     'old', '{mc}'),
  (34, 'Nahum',           'Nah',     'old', '{na}'),
  (35, 'Habakkuk',        'Hab',     'old', '{hb,hab}'),
  (36, 'Zephaniah',       'Zeph',    'old', '{zep,zp}'),
  (37, 'Haggai',          'Hag',     'old', '{hg}'),
  (38, 'Zechariah',       'Zech',    'old', '{zec,zc}'),
  (39, 'Malachi',         'Mal',     'old', '{ml}'),
  (40, 'Matthew',         'Matt',    'new', '{mt,mat}'),
  (41, 'Mark',            'Mark',    'new', '{mk,mr,mrk}'),
  (42, 'Luke',            'Luke',    'new', '{lk,luk}'),
  (43, 'John',            'John',    'new', '{jn,jhn,joh}'),
  (44, 'Acts',            'Acts',    'new', '{ac,act}'),
  (45, 'Romans',          'Rom',     'new', '{ro,rm}'),
  (46, '1 Corinthians',   '1 Cor',   'new', '{1co,1corinth}'),
  (47, '2 Corinthians',   '2 Cor',   'new', '{2co,2corinth}'),
  (48, 'Galatians',       'Gal',     'new', '{ga}'),
  (49, 'Ephesians',       'Eph',     'new', '{ep}'),
  (50, 'Philippians',     'Phil',    'new', '{php,philip,pp}'),
  (51, 'Colossians',      'Col',     'new', '{co,colos}'),
  (52, '1 Thessalonians', '1 Thess', 'new', '{1th,1thes}'),
  (53, '2 Thessalonians', '2 Thess', 'new', '{2th,2thes}'),
  (54, '1 Timothy',       '1 Tim',   'new', '{1ti,1tm}'),
  (55, '2 Timothy',       '2 Tim',   'new', '{2ti,2tm}'),
  (56, 'Titus',           'Titus',   'new', '{tit,ti}'),
  (57, 'Philemon',        'Phlm',    'new', '{phm,philem,plm}'),
  (58, 'Hebrews',         'Heb',     'new', '{hebr}'),
  (59, 'James',           'Jas',     'new', '{jam,jm}'),
  (60, '1 Peter',         '1 Pet',   'new', '{1pe,1pt,1p}'),
  (61, '2 Peter',         '2 Pet',   'new', '{2pe,2pt,2p}'),
  (62, '1 John',          '1 John',  'new', '{1jn,1jo,1jhn,1j}'),
  (63, '2 John',          '2 John',  'new', '{2jn,2jo,2jhn,2j}'),
  (64, '3 John',          '3 John',  'new', '{3jn,3jo,3jhn,3j}'),
  (65, 'Jude',            'Jude',    'new', '{jud,jd}'),
  (66, 'Revelation',      'Rev',     'new', '{re,rv,revelations,apocalypse}')
on conflict (id) do update set
  name = excluded.name,
  abbreviation = excluded.abbreviation,
  testament = excluded.testament,
  aliases = excluded.aliases;

-- An alias that also belongs to another book makes the parser pick one of two
-- books arbitrarily, and the loser is a verse that quietly cannot be looked up
-- by the name its church uses for it. Cheap to check once, here, rather than
-- discovering it from a support message.
do $$
declare
  clash text;
begin
  -- Tokens are de-duplicated WITHIN a book first. Plenty of books are their
  -- own abbreviation -- Job, Ruth, Acts, Jude -- and that is not a clash; two
  -- different books answering to the same token is.
  select string_agg(token, ', ') into clash from (
    select token from (
      select distinct id, lower(btrim(token)) as token from (
        select id, name as token from bible_books
        union all select id, abbreviation from bible_books
        union all select id, unnest(aliases) from bible_books
      ) raw_tokens
    ) per_book
    group by token
    having count(*) > 1
  ) duplicates;

  if clash is not null then
    raise exception 'bible_books has ambiguous name/abbreviation/alias tokens: %', clash;
  end if;
end $$;

-- ============================================================================
-- 3. Verses
-- ============================================================================

create table if not exists bible_verses (
  translation_id text not null
    references bible_translations(id) on delete cascade,
  book_id smallint not null
    references bible_books(id),
  chapter smallint not null check (chapter > 0),
  verse smallint not null check (verse > 0),

  text text not null
    check (length(btrim(text)) > 0),

  -- True where the printed edition starts a new paragraph -- the pilcrow in a
  -- pew Bible. Kept because it is real typographic information about the text
  -- and it costs a bit, not because anything reads it yet.
  paragraph boolean not null default false,

  -- The natural key IS the key. A surrogate id would add a column, an index
  -- and a sequence to a table whose rows are identified by exactly these four
  -- values in every citation ever written. The column order matters: it puts
  -- the index in reading order, so fetching a chapter is one range scan.
  primary key (translation_id, book_id, chapter, verse)
);

-- Full-text search over the words. This is the "find the verse when you can
-- only remember how it goes" half of the feature, and it is why the text lives
-- in Postgres instead of a JSON file in the bundle.
--
-- 'english' stemming is right for the KJV even with its archaic forms: the
-- snowball stemmer folds "loved"/"loveth"-adjacent forms imperfectly but
-- usefully, and a searcher typing "comfort" should find "comforteth". A
-- Tagalog translation added later will want its own configuration on its own
-- rows; that is a reason to make this per-translation when it happens, not a
-- reason to leave it untyped now.
alter table bible_verses
  add column if not exists search tsvector
  generated always as (to_tsvector('english', text)) stored;

create index if not exists bible_verses_search
  on bible_verses using gin (search);

-- Search results are ordered canonically -- Genesis before Revelation -- and
-- the planner needs this to sort a few thousand matches without a full sort of
-- the table.
create index if not exists bible_verses_canonical
  on bible_verses (translation_id, book_id, chapter, verse);

-- ============================================================================
-- 4. The chapter index
--
-- One row per chapter: which chapters a book has, and how many verses each
-- holds. That is everything the chapter and verse grids in the picker need,
-- it is 1,189 rows for the KJV, and it is derived rather than stored, so it
-- cannot drift away from the verses it describes.
-- ============================================================================

create or replace view bible_chapters
with (security_invoker = true) as
  select
    translation_id,
    book_id,
    chapter,
    count(*)::integer as verse_count
  from bible_verses
  group by translation_id, book_id, chapter;

-- ============================================================================
-- 5. Access
--
-- Select for everyone, write for no one. Note there is deliberately no insert,
-- update or delete policy on any of these tables: with RLS on and no policy,
-- those statements match zero rows for every role that goes through RLS. The
-- migration runner and service_role bypass RLS, which is exactly the intended
-- set of writers.
-- ============================================================================

alter table bible_translations enable row level security;
alter table bible_books enable row level security;
alter table bible_verses enable row level security;

drop policy if exists "bible_translations_read" on bible_translations;
create policy "bible_translations_read" on bible_translations
  for select to anon, authenticated using (true);

drop policy if exists "bible_books_read" on bible_books;
create policy "bible_books_read" on bible_books
  for select to anon, authenticated using (true);

drop policy if exists "bible_verses_read" on bible_verses;
create policy "bible_verses_read" on bible_verses
  for select to anon, authenticated using (true);

-- Explicit rather than relying on whatever the default privileges happen to
-- be, and narrow: select only, so a future default that hands out more does
-- not quietly apply to scripture.
revoke all on bible_translations from anon, authenticated;
revoke all on bible_books from anon, authenticated;
revoke all on bible_verses from anon, authenticated;
revoke all on bible_chapters from anon, authenticated;

grant select on bible_translations to anon, authenticated;
grant select on bible_books to anon, authenticated;
grant select on bible_verses to anon, authenticated;
grant select on bible_chapters to anon, authenticated;
